#!/usr/bin/env ruby
# frozen_string_literal: true

require 'slop'

begin
  opts = Slop.parse(ARGV) do |o|
    o.integer '--chunks', 'number of words per cloze', default: 1
    o.banner = 'Usage: anki-cloze [--chunks N] text...'
  end
rescue Slop::Error => e
  warn e.message
  exit 2
end

chunks = opts[:chunks].to_i
chunks = 1 if chunks < 1

# Remaining non-option arguments
words = opts.arguments.flat_map { |a| a.to_s.strip.split(/\s+/) }.reject(&:empty?)

if words.empty?
  puts ''
  exit 0
end

groups = words.each_slice(chunks).to_a
clozes = groups.map.with_index(1) { |g, i| "{{c#{i}::#{g.join(' ')}}}" }
puts clozes.join(' ')

